# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # Specify service dependencies here if necessary
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: zip
          command: |
            pwd
            ls -la
            zip -r lambda.zip . -x '*.git*'
      - store_artifacts:
          path: ./lambda.zip
          destination: lambda.zip
      - persist_to_workspace:
          root: .
          paths:
            - lambda.zip
  deploy:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: sudo apt-get update -y
      - run: sudo apt-get -y -qq install awscli
      - run: ls -la
      - run:
          name: deploy to aws lambda
          command: aws lambda update-function-code --function-name garbageday --region us-east-1 --zip-file fileb://lambda.zip
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
