name: CI-schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: '45 16 * * 4'

  workflow_dispatch:


jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: install deps
        run: pip install -r requirements.txt

      - name: run-schedule
        run: ADDRESS="${{ secrets.ADDRESS }}" SMPT_USERNAME=${{ secrets.SMPT_USERNAME }} SMPT_FROM=${{ secrets.SMPT_FROM }} SMPT_TO=${{ secrets.SMPT_TO }} SMPT_PASS=${{ secrets.SMPT_PASS }} SMPT_DOMAIN=${{ secrets.SMPT_DOMAIN }} python main.py
